name: speech3.9
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9
  - cpuonly
  - pytorch>=1.11.0
  - librosa
  - mne-base
  - scipy
  - numpy>=1.22
  - matplotlib
  - pandas
  - scikit-learn
  - tensorboard
  - h5py
  - tqdm
  - hydra-core
  # dev deps
  - jupyter
  - ipython
  - mypy
  - pytest
variables:
    MEG_DATA: "/home/altukhov/Data/speech/rawdata/derivatives/"
