name: speech3.9
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python==3.9
  - cpuonly
  - pytorch=1.11.0
  - pip
  - librosa
  - mne-base
  - scipy
  - numpy>=1.22
  - matplotlib
  - pandas
  - scikit-learn
  - tensorboard
  - h5py
  - tqdm
  - pip:
    - hydra-core>=1.1.2
    - SoundFile==0.10.3.post1
  # dev deps
  - jupyter
  - ipython
  - mypy
  - pytest
  # --------
variables:
    MEG_DATA: "/home/altukhov/Data/speech/rawdata/derivatives/"
