defaults:
  - paths@paths
  - hydra
  - _self_

deriv_paths: ${paths.01-annotate_premaxfilt}

input:
  raw: ${paths.root_data.raw}
output:
  bad_ch: ${deriv_paths.bad_ch}
  annots: ${deriv_paths.annots}
