defaults:
  - schema
  - paths@paths
  - hydra
  - _self_
  - subject: test

deriv_paths: ${paths.011-annotate_premaxfilt}

input:
  raw: ${paths.root_data.raw}
output:
  bad_ch: ${deriv_paths.bad_ch}
  annots: ${deriv_paths.annots}


lowpass: 100
highpass: null
n_channels: 50
