defaults:
  - paths@paths
  - hydra
  - _self_

deriv_paths: ${paths.02-apply_maxfilter}

input:
  raw: ${paths.root_data.raw}
  ct: ${paths.root_data.ct}
  cal: ${paths.root_data.cal}
  bad_ch: ${paths.01-annotate_premaxfilt.bad_ch}
  annots: ${paths.01-annotate_premaxfilt.annots}
output:
  maxfilt_raw: ${deriv_paths.maxfilt_raw}

t_window: auto
