defaults:
  - paths@paths
  - hydra
  - _self_

deriv_paths: ${paths.03-annotate_postmaxfilt}

input:
  raw: ${paths.02-apply_maxfilter.maxfilt_raw}

output:
  bad_ch: ${deriv_paths.bad_ch}
  annots: ${deriv_paths.annots}
