defaults:
  - paths@paths
  - hydra
  - _self_
  - subject: test

deriv_paths: ${paths.031-annotate_postmaxfilt}

input:
  raw: ${paths.021-apply_maxfilter.maxfilt_raw}

output:
  bad_ch: ${deriv_paths.bad_ch}
  annots: ${deriv_paths.annots}
