defaults:
  - paths@paths
  - hydra
  - _self_

deriv_paths: ${paths.05-inspect_ica}

input:
  raw: ${paths.02-apply_maxfilter.maxfilt_raw}
  ica: ${paths.04-compute_ica.solution}
output:
  bad_ics: ${deriv_paths.bad_ics}

filt:
  l_freq: 1
  h_freq: null
