bids_root: /home/altukhov/Data/speech_meg/rawdata
derivatives: ${.bids_root}/derivatives

subject: test
task: speech

bids_subject: sub-${.subject}
bids_task: task-${.task}

root_data:
  dir: ${..bids_root}
  subj_dir: ${.dir}/${..bids_subject}
  raw: ${.subj_dir}/meg/${..bids_subject}_${..bids_task}_meg.fif
  ct: ${.subj_dir}/meg/${..bids_subject}_acq-crosstalk_meg.fif
  cal: ${.subj_dir}/meg/${..bids_subject}_acq-calibration_meg.dat

01-annotate_premaxfilt:
  dir: ${..derivatives}/01-annotate_premaxfilt
  subj_dir: ${.dir}/${..bids_subject}
  base: ${..bids_subject}_${..bids_task}
  bad_ch: ${.subj_dir}/${.base}_bads.tsv
  annots: ${.subj_dir}/${.base}_annot.fif

02-apply_maxfilter:
  dir: ${..derivatives}/02-apply_maxfilt
  subj_dir: ${.dir}/${..bids_subject}
  base: ${..bids_subject}_${..bids_task}_proc-maxfilt
  maxfilt_raw: ${.subj_dir}/${.base}_meg.fif

03-annotate_postmaxfilt:
  dir: ${..derivatives}/03-annotate_postmaxfilt
  subj_dir: ${.dir}/${..bids_subject}
  base: ${..02-apply_maxfilter.base}
  bad_ch: ${.subj_dir}/${.base}_bads.tsv
  annots: ${.subj_dir}/${.base}_annot.fif

04-compute_ica:
  dir: ${..derivatives}/04-compute_ica
  subj_dir: ${.dir}/${..bids_subject}
  base: ${..02-apply_maxfilter.base}
  solution: ${.subj_dir}/${.base}_ica.fif
  report: ${.subj_dir}/${.base}_ica.html
