bids_root: /home/altukhov/Data/speech_meg/rawdata
derivatives_path: ${bids_root}/derivatives

subject: test
task: speech

bids_subject: sub-${subject}
bids_task: task-${task}

raw_path: ${bids_root}/${bids_subject}/meg/${bids_subject}_${bids_task}_meg.fif
ct_path: ${bids_root}/${bids_subject}/meg/${bids_subject}_acq-crosstalk_meg.fif
cal_path: ${bids_root}/${bids_subject}/meg/${bids_subject}_acq-calibration_meg.dat
